// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXZT_uqL4vWjrpgC7XgAqfnp8Zir3_sE',
    appId: '1:436538113067:web:65e6a8a0ac84a7c3f7fe6e',
    messagingSenderId: '436538113067',
    projectId: 'app-gestao-horas-servidores',
    authDomain: 'app-gestao-horas-servidores.firebaseapp.com',
    storageBucket: 'app-gestao-horas-servidores.firebasestorage.app',
    measurementId: 'G-VY44L4NJ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMBggbrow37w0E8gLZU5wlSz4woX4xrs',
    appId: '1:436538113067:android:4def1ffda33bc504f7fe6e',
    messagingSenderId: '436538113067',
    projectId: 'app-gestao-horas-servidores',
    storageBucket: 'app-gestao-horas-servidores.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoWf4E4AsxO2aplJM_dmCZRsQjkDoR7E',
    appId: '1:436538113067:ios:db9dba5483cf254bf7fe6e',
    messagingSenderId: '436538113067',
    projectId: 'app-gestao-horas-servidores',
    storageBucket: 'app-gestao-horas-servidores.firebasestorage.app',
    androidClientId: '436538113067-t8es4i2vpne88dnn1vugk5ujhp0inu3q.apps.googleusercontent.com',
    iosClientId: '436538113067-4n4pte1dj0adej3p616q45qvnv1j6npe.apps.googleusercontent.com',
    iosBundleId: 'br.com.shiroshima.gestorHorasExtras',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyoWf4E4AsxO2aplJM_dmCZRsQjkDoR7E',
    appId: '1:436538113067:ios:db9dba5483cf254bf7fe6e',
    messagingSenderId: '436538113067',
    projectId: 'app-gestao-horas-servidores',
    storageBucket: 'app-gestao-horas-servidores.firebasestorage.app',
    androidClientId: '436538113067-t8es4i2vpne88dnn1vugk5ujhp0inu3q.apps.googleusercontent.com',
    iosClientId: '436538113067-4n4pte1dj0adej3p616q45qvnv1j6npe.apps.googleusercontent.com',
    iosBundleId: 'br.com.shiroshima.gestorHorasExtras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQXZT_uqL4vWjrpgC7XgAqfnp8Zir3_sE',
    appId: '1:436538113067:web:c40256028e539d01f7fe6e',
    messagingSenderId: '436538113067',
    projectId: 'app-gestao-horas-servidores',
    authDomain: 'app-gestao-horas-servidores.firebaseapp.com',
    storageBucket: 'app-gestao-horas-servidores.firebasestorage.app',
    measurementId: 'G-8CTRTJSB7N',
  );
}
